import type {
  CrimeIncident,
  EvidenceSource,
  CourtCase,
  JudgeProfile,
  AdminReviewItem,
} from "./types";

export const MOCK_INCIDENTS: CrimeIncident[] = [
  {
    id: "inc-001",
    title: "Alleged Contract Fraud — Municipal Procurement",
    summary:
      "A senior municipal official is alleged to have steered a $4.2M infrastructure contract to a company with undisclosed ties. Complaint filed with the provincial integrity commissioner; investigation ongoing.",
    category: "fraud",
    status: "alleged",
    confidence: "medium",
    date: "2024-09-14",
    location: {
      lat: 43.6532,
      lng: -79.3832,
      precision: "city",
      city: "Toronto",
      province: "Ontario",
      country: "Canada",
    },
    sourceCount: 3,
    evidenceCount: 5,
    linkedCases: ["case-001"],
    linkedJudges: [],
    linkedDefendants: ["def-001"],
    tags: ["procurement", "municipal", "integrity"],
    sensitive: false,
  },
  {
    id: "inc-002",
    title: "Judicial Conduct Complaint — Bias Allegation",
    summary:
      "A formal complaint was filed with the Canadian Judicial Council alleging a pattern of biased rulings in a series of family court cases. The complaint was accepted for review.",
    category: "misconduct",
    status: "before_court",
    confidence: "high",
    date: "2024-11-03",
    location: {
      lat: 45.4215,
      lng: -75.6972,
      precision: "city",
      city: "Ottawa",
      province: "Ontario",
      country: "Canada",
    },
    sourceCount: 5,
    evidenceCount: 8,
    linkedCases: ["case-002"],
    linkedJudges: ["judge-001"],
    linkedDefendants: [],
    tags: ["judicial_conduct", "family_court", "cjc"],
    sensitive: false,
  },
  {
    id: "inc-003",
    title: "Corruption Charges — Police Misconduct",
    summary:
      "Three officers were charged with breach of trust and obstruction of justice following an internal affairs investigation into evidence tampering in narcotics cases.",
    category: "corruption",
    status: "charged",
    confidence: "high",
    date: "2025-01-22",
    location: {
      lat: 45.5017,
      lng: -73.5673,
      precision: "city",
      city: "Montréal",
      province: "Québec",
      country: "Canada",
    },
    sourceCount: 7,
    evidenceCount: 12,
    linkedCases: ["case-003"],
    linkedJudges: ["judge-002"],
    linkedDefendants: ["def-002", "def-003"],
    tags: ["police", "breach_of_trust", "narcotics"],
    sensitive: false,
  },
  {
    id: "inc-004",
    title: "Organized Crime Sentencing — RICO-Style Prosecution",
    summary:
      "Following a multi-year investigation, 11 individuals were convicted on organized crime charges. Sentencing is pending and is expected to set a provincial precedent.",
    category: "organized_crime",
    status: "convicted",
    confidence: "high",
    date: "2025-03-10",
    location: {
      lat: 49.2827,
      lng: -123.1207,
      precision: "city",
      city: "Vancouver",
      province: "British Columbia",
      country: "Canada",
    },
    sourceCount: 11,
    evidenceCount: 23,
    linkedCases: ["case-004"],
    linkedJudges: ["judge-003"],
    linkedDefendants: ["def-004"],
    tags: ["organized_crime", "multi-year", "precedent"],
    sensitive: false,
  },
  {
    id: "inc-005",
    title: "Dismissed: Financial Misconduct Allegation",
    summary:
      "Charges of financial misconduct against a provincial legislator were dismissed after the Crown withdrew the case citing insufficient evidence. The decision was contested by advocacy groups.",
    category: "corruption",
    status: "dismissed",
    confidence: "medium",
    date: "2024-07-30",
    location: {
      lat: 51.0447,
      lng: -114.0719,
      precision: "city",
      city: "Calgary",
      province: "Alberta",
      country: "Canada",
    },
    sourceCount: 4,
    evidenceCount: 6,
    linkedCases: [],
    linkedJudges: [],
    linkedDefendants: ["def-005"],
    tags: ["financial", "legislator", "dismissed"],
    sensitive: false,
  },
];

export const MOCK_EVIDENCE_SOURCES: EvidenceSource[] = [
  {
    id: "src-001",
    name: "Toronto Star — Investigative Report (Sept 2024)",
    url: "https://example.com/torstar-2024-09",
    type: "news_report",
    confidence: "high",
    publishedAt: "2024-09-18",
    summary:
      "Investigative report detailing the procurement process and identified conflicts of interest.",
    verified: true,
    claims: [
      "Contract awarded without competitive tender",
      "Relationship between official and contractor disclosed after award",
    ],
  },
  {
    id: "src-002",
    name: "Ontario Integrity Commissioner — Case File #2024-088",
    type: "government_document",
    confidence: "high",
    publishedAt: "2024-10-01",
    summary: "Formal acceptance of complaint and notice of investigation.",
    verified: true,
    claims: ["Complaint accepted for investigation", "Interim preservation order issued"],
  },
  {
    id: "src-003",
    name: "Canadian Judicial Council — Notice of Review",
    type: "government_document",
    confidence: "high",
    publishedAt: "2024-11-15",
    summary: "CJC formal notice confirming complaint was accepted for review.",
    verified: true,
    claims: [
      "Complaint received and assessed",
      "Matter referred to inquiry committee",
    ],
  },
  {
    id: "src-004",
    name: "CBC News — Court Filing Summary",
    url: "https://example.com/cbc-filing",
    type: "news_report",
    confidence: "medium",
    publishedAt: "2025-01-25",
    summary: "Summary of charges filed and preliminary court dates.",
    verified: false,
    claims: ["Three officers named in charge sheet", "Bail hearings set for February"],
  },
  {
    id: "src-005",
    name: "BC Court Services Online — Judgment (2025 BCSC 412)",
    url: "https://example.com/bcsc-2025-412",
    type: "court_record",
    confidence: "high",
    publishedAt: "2025-03-14",
    summary: "Official court record of conviction and sentencing details.",
    verified: true,
    claims: [
      "11 individuals convicted on all counts",
      "Sentencing scheduled for June 2025",
    ],
  },
  {
    id: "src-006",
    name: "Transparency International Canada — Annual Report 2024",
    type: "ngo_report",
    confidence: "medium",
    publishedAt: "2024-12-01",
    summary: "Annual analysis of public corruption cases in Canadian jurisdictions.",
    verified: false,
    claims: ["Pattern identified across multiple municipalities", "Systemic issue noted"],
  },
];

export const MOCK_JUDGES: JudgeProfile[] = [
  {
    id: "judge-001",
    name: "Hon. M. Leblanc",
    court: "Ontario Court of Justice",
    jurisdiction: "Ontario",
    appointedAt: "2015-04-10",
    status: "active",
    linkedCases: ["case-002"],
    allegedMisconductCount: 1,
    sourceCount: 5,
    notes: "Subject of CJC formal review; continues to preside pending outcome.",
  },
  {
    id: "judge-002",
    name: "Hon. R. Okonkwo",
    court: "Superior Court of Québec",
    jurisdiction: "Québec",
    appointedAt: "2011-09-01",
    status: "active",
    linkedCases: ["case-003"],
    allegedMisconductCount: 0,
    sourceCount: 3,
  },
  {
    id: "judge-003",
    name: "Hon. S. Whitmore",
    court: "British Columbia Supreme Court",
    jurisdiction: "British Columbia",
    appointedAt: "2008-03-22",
    status: "retired",
    linkedCases: ["case-004"],
    allegedMisconductCount: 0,
    sourceCount: 7,
  },
];

export const MOCK_CASES: CourtCase[] = [
  {
    id: "case-001",
    caseNumber: "ON-INT-2024-088",
    title: "Integrity Complaint re: Municipal Contract Irregularities",
    status: "before_court",
    court: "Ontario Integrity Commissioner",
    jurisdiction: "Ontario",
    filedAt: "2024-09-20",
    charges: ["Breach of public trust", "Undisclosed conflict of interest"],
    linkedJudges: [],
    linkedDefendants: ["def-001"],
    linkedIncidents: ["inc-001"],
    evidenceSources: [MOCK_EVIDENCE_SOURCES[0], MOCK_EVIDENCE_SOURCES[1]],
  },
  {
    id: "case-002",
    caseNumber: "CJC-2024-FR-5521",
    title: "Canadian Judicial Council Formal Review",
    status: "before_court",
    court: "Canadian Judicial Council",
    jurisdiction: "Federal",
    filedAt: "2024-11-03",
    charges: ["Judicial bias", "Conduct unbecoming"],
    linkedJudges: ["judge-001"],
    linkedDefendants: [],
    linkedIncidents: ["inc-002"],
    evidenceSources: [MOCK_EVIDENCE_SOURCES[2]],
  },
  {
    id: "case-003",
    caseNumber: "QC-CRIM-2025-0089",
    title: "R v. Beaumont et al. — Breach of Trust",
    status: "charged",
    court: "Superior Court of Québec",
    jurisdiction: "Québec",
    filedAt: "2025-01-24",
    charges: ["Breach of trust (s. 122 CC)", "Obstruction of justice (s. 139 CC)"],
    linkedJudges: ["judge-002"],
    linkedDefendants: ["def-002", "def-003"],
    linkedIncidents: ["inc-003"],
    evidenceSources: [MOCK_EVIDENCE_SOURCES[3]],
  },
  {
    id: "case-004",
    caseNumber: "2025 BCSC 412",
    title: "R v. Tremblay-Chen et al. — Organized Crime Convictions",
    status: "convicted",
    court: "British Columbia Supreme Court",
    jurisdiction: "British Columbia",
    filedAt: "2022-06-01",
    resolvedAt: "2025-03-10",
    charges: [
      "Participation in criminal organization (s. 467.11 CC)",
      "Drug trafficking",
      "Money laundering",
    ],
    outcome: "Convicted on all counts. Sentencing pending.",
    linkedJudges: ["judge-003"],
    linkedDefendants: ["def-004"],
    linkedIncidents: ["inc-004"],
    evidenceSources: [MOCK_EVIDENCE_SOURCES[4], MOCK_EVIDENCE_SOURCES[5]],
  },
];

export const MOCK_ADMIN_REVIEW_ITEMS: AdminReviewItem[] = [
  {
    id: "rev-001",
    type: "incident",
    title: "New incident submission: Alleged bribery — Halifax Zoning Board",
    submittedAt: "2025-05-01T09:12:00Z",
    submittedBy: "anonymous",
    status: "pending",
    priority: "medium",
  },
  {
    id: "rev-002",
    type: "source",
    title: "Source addition: Global News article re: QC corruption",
    submittedAt: "2025-04-30T14:44:00Z",
    submittedBy: "research@example.org",
    status: "pending",
    priority: "low",
  },
  {
    id: "rev-003",
    type: "correction",
    title: "Correction request: Date error in inc-003",
    submittedAt: "2025-04-29T11:00:00Z",
    submittedBy: "anonymous",
    status: "needs_info",
    priority: "low",
    notes: "Submitter claims incident date should be Jan 21, not Jan 22.",
    entityId: "inc-003",
  },
  {
    id: "rev-004",
    type: "case",
    title: "New case link: Connect case-003 to additional incidents",
    submittedAt: "2025-04-28T16:20:00Z",
    submittedBy: "investigator@ngo.ca",
    status: "approved",
    priority: "high",
    entityId: "case-003",
  },
  {
    id: "rev-005",
    type: "incident",
    title: "New incident: Fraud allegation — Saskatoon health authority",
    submittedAt: "2025-04-27T10:05:00Z",
    status: "pending",
    priority: "high",
  },
];

// Helper maps for quick lookup
export const INCIDENT_MAP: Record<string, CrimeIncident> = Object.fromEntries(
  MOCK_INCIDENTS.map((i) => [i.id, i])
);
export const JUDGE_MAP: Record<string, JudgeProfile> = Object.fromEntries(
  MOCK_JUDGES.map((j) => [j.id, j])
);
export const CASE_MAP: Record<string, CourtCase> = Object.fromEntries(
  MOCK_CASES.map((c) => [c.id, c])
);
